### ISSUE TITLE
TypeError: Cannot read property 'iso_code' of undefined

### ISSUE THREAD

**Issue by vatex** [fcambus/telize#15]
TypeError: Cannot read property 'iso_code' of undefined
    at Satelize.satelize (/var/app/current/node_modules/satelize/src/satelize.js:42:33)
    at module.exports.test (/var/app/current/test/file.js:109:14)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:302:13)
    at /var/app/current/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/var/app/current/node_modules/express/lib/router/index.js:321:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:261:10)
    at next (/var/app/current/node_modules/express/lib/router/route.js:100:14)
    at next (/var/app/current/node_modules/express/lib/router/route.js:104:14)
    at next (/var/app/current/node_modules/express/lib/router/route.js:104:14)
    at next (/var/app/current/node_modules/express/lib/router/route.js:104:14)
    at next (/var/app/current/node_modules/express/lib/router/route.js:104:14)
    at next (/var/app/current/node_modules/express/lib/router/route.js:104:14)
    at next (/var/app/current/node_modules/express/lib/router/route.js:104:14)
    at next (/var/app/current/node_modules/express/lib/router/route.js:104:14)
    at next (/var/app/current/node_modules/express/lib/router/route.js:104:14)

**Comment by fcambus** [comment]
Wrong repository.
